### ISSUE TITLE
Directory/file browser website

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/web-cdn#20]
Allow us to see what all is in the CDN.

Here's what I'm thinking:

The site will have a .cdn-config.yml like any other library.  The main-config.yml file would then have this entry:

```yml
cdn:
  site:
    source: github:byuweb/cdn-site
```
